### PR TITLE
Slovak localization (partial)

### PR DESCRIPTION
**Pull request by Matej4386**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
Partial Slovak localization

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @Matej4386!
Thank you very much for adding the localization!
We have added scripts to automatically translate English to Slovak... And now the PR you've created has conflicts with the dev branch.
I looked at the differences - and there are actual differences between auto translation and your manual translation.
Could you please verify the localization and update the PR?
Sorry for asking you to do additional job...

**Comment by Matej4386** [comment]
Hi @AJIXuMuK,
thank for information. I have just looked at conflicts and there are some bad automatic translation, but it is better than mine :-) 
I do not have access this month to update PR :-( I have just found these mistakes:

"TaxonomyPickerInLabel": "Palcov", - "v"
"WebPartTitleLabel": "Pridanie titulu", - "Pridanie nádpisu"
"peoplePickerLoadingText": "Nakládky", - "Nahrávanie"
"peoplePickerSuggestionsHeaderText": "Navrhovaných ľudí", - "Navrhovaní ľudia"
"ListItemAttachmentsdialogOKbuttonLabel": "ok", - "OK"
"mapsLoadingText": "Nakládky", - ""Nahrávanie"
"AlignCenter": "Centrum", - "Zarovnať na stred"
"ThemeColorDarker": "Téma tmavšie", -> "Tmavšia téma"
"ThemeColorDark": "Tematický motív", -> "Tmavá téma"
"ThemeColorDarkAlt": "Motív tmavý náhradník", -> "Alternatívna tmavá téma"
"ThemeColorPrimary": "Téma primárne",  -> "Primárna téma"
"ThemeColorSecondary": "Téma sekundárne",  -> "Sekundárna téma"
"ThemeColorTertiary": "Neutrálne terciárne",  -> "Ďalšia téma"
"ThemeColorNeutralSecondary": "Neutrálne sekundárne",  -> "Neutrána sekundárna téma"
"ThemeColorNeutralPrimaryAlt": "Neutrálny primárny náhradník",  -> "Alternatívna primárna téma"
"ThemeColorNeutralPrimary": "Neutrálne primárne",  -> "Neutrána primárna téma"
"ThemeColorNeutralDark": "Neutrálna tmavá", -> "Neutrálna tmavá téma"
"HighlightColorYellow": "Žlté",  -> "Žltá"
"HighlightColorAqua": "Aqua",  -> "Bledomodrá"
"HighlightColorMagenta": "Purpurová",
"HighlightColorBlue": "Blue", -> "Modrá"
"HighlightColorRed": "Červené", -> "Červená" 
"HighlightColorDarkblue": "Tmavo modré", -> "Tmavomodrá"
"HighlightColorTeal": "Teal",-> "Zelenomodrá"
"HighlightColorMaroon": "Maroon",- "Gaštanovohnedá"
"HighlightColorGold": "Zlato",- "Zlatá"
"StandardColorRed": "Červené", - "Červená"
"StandardColorYellow": "Žlté", - "Žltá"
"StandardColorBlue": "Blue",- "Modrá"
"StandardColorDarkblue": "Tmavo modré",- "Tmavo modrá" 
"DatePickerMonthLongJanuary": "Januári",- "Január"
"DatePickerMonthShortJanuary": "Január"  - "Jan"
"DatePickerMonthLongFebruary": "Februári",- "Február" 
"DatePickerMonthShortFebruary": "Február", - "Feb"
"DatePickerMonthLongMarch": "Marca", - "Marec"
"DatePickerMonthShortMarch": "Mar", 
"DatePickerMonthLongApril": "Apríli",- "Apríl" 
"DatePickerMonthShortApril": "Apríla",-"Apr"
"DatePickerMonthLongMay": "Môže",- "Máj"
"DatePickerMonthShortMay": "Môže",- "Máj"
"DatePickerMonthLongJune": "Júni",- "Jún"
"DatePickerMonthShortJune": "Júna",- "Jún"
"DatePickerMonthLongJuly": "Júli", - "Júl"
"DatePickerMonthShortJuly": "Júl", - "Júl
"DatePickerMonthLongAugust": "Auguste", - "August"
"DatePickerMonthShortAugust": "Augusta",- "Aug"
"DatePickerMonthLongSeptember": "Septembra", - "September"
"DatePickerMonthShortSeptember": "Sedem", - "Sep"
"DatePickerMonthLongOctober": "Októbri",- "Október"
"DatePickerMonthShortOctober": "Október", - "Okt"
"DatePickerMonthLongNovember": "Novembri", - "November"
"DatePickerMonthShortNovember": "Novembra", - "Nov"
"DatePickerMonthLongDecember": "Decembri",- "December"
"DatePickerMonthShortDecember": "Decembra",- "Dec"
"DatePickerDayLongSunday": "Nedeľu", - "Nedeľa"
"DatePickerDayShortSunday": "Slnko", - "Ne"
"DatePickerDayShortMonday": "Môj",  - "Po"
"DatePickerDayLongTuesday": "Utorok",  
"DatePickerDayShortTuesday": "Tue",  - "Ut"
"DatePickerDayLongWednesday": "Stredu",  - "Streda"
"DatePickerDayShortWednesday": "St",  
"DatePickerDayLongThursday": "Štvrtok",  
"DatePickerDayShortThursday": "Št",  
"DatePickerDayLongFriday": "Piatok",
"DatePickerDayShortFriday": "Pi",
"DatePickerDayLongSaturday": "Sobotu", - "Sobota"
"DatePickerDayShortSaturday": "Sedel", - "So"
"Loading": "Nakládky...", - "Načítava sa ..."
"SortedAscending": "Zoradené do Z", - "Zoradené vzostupne"
"SortedDescending": "Zoradené Z na", - "Zoradené zostupne"

**Comment by AJIXuMuK** [comment]
Thank you for the summary of the mistakes.
But I would prefer to wait until you have access to the PR :) 
As I'm not a native Slovak speaker - I don't want to mess things up :)

**Comment by Matej4386** [comment]
Hello @AJIXuMuK,
now it should be better ;-)

**Comment by AJIXuMuK** [comment]
Thanks @Matej4386  for updating the translation!

**Pull request merged**
