### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by russgove**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Implement Grouping in ListView

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks @russgove will try to test it out this week.

**Comment by estruyf** [comment]
@russgove I did some tests and there are various problems so I cannot merge it.

- debugger statements
- findIndex method cannot be found because you switched to lodash
- grouping not correct
- sorting not correct

**Comment by estruyf** [comment]
I rewrote grouping for the ListView control. If you want to test it out, it is available in the DEV branch: https://github.com/SharePoint/sp-dev-fx-controls-react/tree/dev

**Comment by russgove** [comment]
Ill check it out  today

**Comment by russgove** [comment]
Still Some Issues. I have my test data set up like this:
[image: Inline image 1]

Want To group by Field1 and Field 2 so i set it to
const groupByFields: string[] = ["ListItemAllFields.Field1",
"ListItemAllFields.Field2"];

When I load the test webpart I see this
[image: Inline image 2]

Doc B1 is in the B2 group.
Also, I think it should sort ascending by whatever we group on and be
collapsed (or let user specify)

**Comment by estruyf** [comment]
Something went wrong with your images, can you re-upload them, please.

Sorting is achieved per group.

**Comment by estruyf** [comment]
I think I found the bug. Did an update, if you have time to check it out, that would be wonderful.

**Comment by russgove** [comment]
Ok, I tested it out and the items are showing in  the correct groups now.
But  the groups start out in reverse  Order:


[image: Inline image 1]



and when I click on the title to sort , The Groups get sorted:
[image: Inline image 2]

The way I think it should work is that the groups are 'constant'.  sorting
columns does not change the sequence of the groups, just the order of the
items within the groups.

**Comment by estruyf** [comment]
The order of the groups should now be fixed. Also added the ability to tell how you want to sort the groups: ascending or descending.

**Pull request closed without merging**
