### PR TITLE
People Picker react control

### PR DESCRIPTION
**Pull request by AsishP**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ X]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
Peoplepicker react control

#### Guidance
There is a sample tag in Control test page for testing. The people picker control also supports mandatory requirement and tooltip

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks @AsishP I will process this as soon as possible.

**Comment by AsishP** [comment]
Thanks @estruyf, please let me know if there are any queries or feedback.

**Comment by AsishP** [comment]
Hi @estruyf, I have resolved the conflict and merged the files, please let me know if there is anything else.

**Comment by AsishP** [comment]
Hi @estruyf, is there anything missing in the control that I need to add or modify? Please let me know.
I have few contacts who are waiting to use the control when ready. Thanks.

**Comment by estruyf** [comment]
Sorry @AsishP, did not had the time yet to process it. I had to postpone it to the next release, because of the PnP Starters Kit.

**Comment by estruyf** [comment]
@AsishP I just started testing out your control, and ran into some issues:
- When no group is specified, I cannot retrieve people. I like that you have implemented it to retrieve users from a specific group, but it would be nice if none is specified, it will check all users like in the property pane control.
- There are a couple of `console.log` defined, better to remove these.
- Documentation is missing for the control. Would you be able to add it to the PR?

**Comment by AsishP** [comment]
Hi @estruyf , the all users functionality is included. It works when the `getAllUsers` is set to true. However I get the confusion because of two properties. May be I will set the setting to if `groupName` is empty, then get all users instead. Does it sound ok?

I have started looking into the documentation bit and will update the PR soon. Thanks.

**Comment by estruyf** [comment]
It might indeed be easier to only specify the groupName property, if not provides, you fetch all.

**Comment by estruyf** [comment]
@AsishP any new updates?

**Comment by AsishP** [comment]
Hi @estruyf, 
Yeah I am done with the updates on the code but facing issues with mkdocs. I am not able to serve mkdocs from docs/documentation folder. I get the below issue. Seems like my path variables are correct, don't know what I am missing.
Would you know what is going wrong?

image

```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\nav.py", line 337, in _follow
    raise StopIteration
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\users\asish\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\asish\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 127, in serve_command
    livereload=livereload
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\serve.py", line 117, in serve
    config = builder()
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 213, in build_pages
    site_navigation = nav.SiteNavigation(config)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\nav.py", line 44, in __init__
    config, self.url_context)
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\nav.py", line 392, in _generate_site_navigation
    config_line, url_context, config):
  File "c:\users\asish\appdata\local\programs\python\python37\lib\site-packages\mkdocs\nav.py", line 356, in _follow
    for sub in _follow(path, url_context, config, header=header, title=next_cat_or_title):
RuntimeError: generator raised StopIteration

```

**Comment by estruyf** [comment]
It is good enough to write the markdown files, these can be checked within VSCode with the `markdown preview` option. I'll check if everything is ok with `mkdocs`.

**Comment by AsishP** [comment]
Thanks @estruyf, I have submitted the change with documentation. Please test and let me know.

**Comment by estruyf** [comment]
Thanks @AsishP I did some changes to align to code to other controls. This has now been merged into the DEV branch and planned for the v1.5.0 release.

**Comment by AsishP** [comment]
Thanks @estruyf

**Pull request merged**
