### PR TITLE
Field picker list data

### PR DESCRIPTION
**Pull request by joaojmendes**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ X]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

reusable control using @PnP/PnpJs, Office-ui-fabric-react control, that consist of select value as you type from a list column data. This is util when you have large list of items.

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks @joaojmendes for this PR. Always great to receive new controls. I will align this with the current code base. Would it be possible to also add documentation about how to use this control like you can find here: https://github.com/SharePoint/sp-dev-fx-controls-react/tree/master/docs/documentation/docs/controls/fields - Best to do this in a new PR, that way I can do the code changes.

**Comment by estruyf** [comment]
Merge is completed @joaojmendes for this PR. You can check out the changes I did. Once your documentation PR is in, I can release this version soon after it.

**Comment by joaojmendes** [comment]
Hi Elio thank you very much for your help and guidance.

Yes I agree with your suggestions.

Thanks.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by joaojmendes** [comment]
Hi,

I created documentation to ListItemPicker control and did some code fixes.

Thank you!

**Pull request merged**
