### PR TITLE
Initial version of the GridLayout control

### PR DESCRIPTION
**Pull request by hugoabernier**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | 
| Related pull request | #351

#### What's in this Pull Request?

A GridLayout control to simplify rendering web parts with the standard grid layout. Intended to be really easy to use and handles reflowing content and compact layout.

Sample Grid Layout

Sample reflowing

### CODE REVIEW

**Comment by hugoabernier** [comment]
Sorry, I just realize I created my branch from the `master` branch instead of `dev`. I'll do better next time :-)

**Comment by hugoabernier** [comment]
@estruyf I'm planning on adding components for the other standard web part layouts (e.g.: filmstrip, compact, etc.) as per [the SharePoint Design layout patterns](https://docs.microsoft.com/en-us/sharepoint/dev/design/layout-patterns). 

I'm planning on submitting each one as a separate PR. Would you prefer them as a single PR?

**Comment by estruyf** [comment]
Thank you @hugoabernier, merged it to the DEV branch.

**Comment by estruyf** [comment]
Something seems wrong with the Github merging. I manually merged it, code should be fine, but Github doesn't know the source location it seems.

**Comment by hugoabernier** [comment]
@estruyf  I can resubmit as a single 'layout' control instead of individual 'grid', 'filmstrip', 'compact', 'carousel' layouts.

**Comment by estruyf** [comment]
This grid control has already been merged so all good here.

**Pull request closed without merging**
