### PR TITLE
update to spfx 1.6.0

### LINKED ISSUE #144: spfx v 1.6
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

I am thinking about adding some functionality to the people picker to grab data from the graph. This requires SPFx 1.6 or greater. Also will have to add some webApiPermissionRequests or at least some documentation to set it up if people want to use that functionality.  Perhaps a setting UseGraph or PeopleSource property to define where the data is coming from.

Any reason why we cant upgrade the solution to SPFx1.6?

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #144 

#### What's in this Pull Request?

Update to 1.6.0

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks @joelfmrodrigues, will wait for the next release to merge this. As this is a breaking change. So all fixes and enhancements will still be available in for the older projects.

**Comment by estruyf** [comment]
@joelfmrodrigues based on the usage, the controls are still used a lot in older SPFx versions. So we first need to provide fixes to the current version. After that, we could start thinking about creating version `2.0.0`.

**Comment by joelfmrodrigues** [comment]
Sure, I completely understand that :)
I updated both reusable controls projects to test the Office 365 CLI upgrade as I needed it for a client project. So decided to give the reusable controls projects a try as they are fairly big and used them as a test for me :)

**Comment by estruyf** [comment]
@joelfmrodrigues going to close this one. We'll wait until the next version of SharePoint Framework to see what the TypeScript version dependency will be. When they bump this to version `3.x` it will be time to bump the controls version to `2.x` and add support for Office UI Fabric version 6. This will probably have a major impact on what has already been created (style changes / property changes / helper functions that are not necessary anymore / ...), and will mean that version 2 will only support SharePoint Online.

**Pull request closed without merging**
