### PR TITLE
Implementing People Picker to search all user profiles and not just current site (#97)

### PR DESCRIPTION
**Pull request by AsishP**
| Q               | A
| --------------- | ---
| Bug fix?        | [X ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | Implements People search for all tenant users as mentioned in #97 

#### What's in this Pull Request?
The items implemented in this PR:
1. Search across All Users instead of only this site by default.
2. Added resolveDelay to allow search of users across the tenant
3. Binding defaultUsers to non existent site users
4. Updated Documentation with details for resolveDelay and added Principal type

### CODE REVIEW

**Comment by sympmarc** [comment]
@estruyf - I'd love to test this PR. Any idea when it might end up in a beta?

**Comment by estruyf** [comment]
@sympmarc will try to process this later tonight. There are some changes required before this can be merged.

@AsishP thanks again for the updates. The value of `all` should be `15`, not `13`, but it might be better to not include this. As it could create conflicts if you specify for instance `[User, All]`.

**Comment by estruyf** [comment]
It feels that the control is a mix of everything right now. Will require a bit more time in order to rewrite it. 

Example:
- On initial load, the users are retrieved from the site users endpoint
- On search, the users are retrieved from the tenant

IMO we have to go for a similar implementation like in the property pane control. When a site URL is provided it, it searches against the current site. When the site URL isn't provided, it searches over the whole tenant.

@AsishP @sympmarc thoughts?

**Comment by sympmarc** [comment]
Sounds right to me. Ideally, the property pane and this one should work the same (as I suggested in the associated issue) - and should probably share code, if that works. End result should be a people picker that works like any other people picker.

**Comment by AsishP** [comment]
@estruyf , sorry, yeah it should have been 15 don't know why I had left it to 13, I was testing something and forgot to change it back. Updated it back to 15. 

Regarding the logic, I suppose the code is doing as stated in your example. It loads the users from default site on load and then searches from tenant on Inputchange of people picker control. Below the logic in the code at present, please let me know if anything is amiss. Would love to fix any gaps to make it efficient and better. Please suggest.

1. The users are prefilled from site on load for existing site users and userid for existing users and put into the state.
2. Regarding default users, the users are filled from site users and if not present, they are pulled from tenant and updated to state for the control.
3. For non-existent users, search from tenant users (got the idea from property control implementation approach) on InputChange method and then update the state with new users if not present. 
In step 3, since there is a delay for search to return users so had to add a resolveDelay for 1 sec to allow the filter to work. Might there is a better approach here.

Thoughts, suggestions?

**Comment by estruyf** [comment]
@AsishP the option should be at the developer from which source he/she wants to retrieve the data. I like the prefilling idea, but I think it's unnecessary. If the user wants to retrieve data from the tenant, the prefilling should be skipped, as data should come from the tenant search.

When the developer wants to limit data only from the current site, the tenant search should be skipped.

So for your suggestions:
1. Don't feel that we need prefilling, or only when the dev wants to receive data from the current site.
2. Should be defined by the dev from which scope he wants to retrieve data.
3. ...

I think it might be better to completely redevelop the control. Just like @sympmarc said to have the same behavior as in the property pane control.

**Comment by estruyf** [comment]
@AsishP and @sympmarc the control has completely been rewritten. When the `webAbsoluteUrl` property is provided, the people search will be done on the site level. When not provided, this will be at the tenant level.

The code is also simplified + removed a lot of unused state properties. Let me know what is missing or needs to be changed.

New beta version is available for testing.

**Comment by AsishP** [comment]
Ok, let me check the property pane control in detail then to see the flow. I did give it a quick check earlier but not a detailed study. To confirm, this is my understanding on the flow right now.
1. Developers could choose between All Tenant, All Site or Site Group.
2. For All Tenant users, there will be no auto suggestions till search is done for first three characters. The match will be done after third character and fill the state with matches so to speed up future filtering.
3. Will keep the same pre-fill users logic, as the user could be at site or tenant but giving preference to site.

@sympmarc, please give some time for the above to be implemented. @estruyf, I see some conflicts in my PR, so just confirming are these changes with regards to this PR or something else.

**Comment by AsishP** [comment]
Sorry, seems my message came later after @estruyf message. Thanks @estruyf, for the update. Please let me know if I should close this PR.

**Comment by estruyf** [comment]
@AsishP yes, you should best get the latest DEV version, as a lot has been replaced, rewritten, ... 

About point 2, this is indeed a limitation of the API, but don’t feel that this is an issue. As the most of the time you will search, and the proposed once will not be used. 

About point 3, pre-fill logic is implemented if you are retrieving from the site/group. 

We can keep the PR open to discuss it, or we could do it in a new issue. Your call.

**Comment by ManiKum** [comment]
@estruyf , with beta build, the search is happening on entire tenant (as we were expecting). However, the selected item's properties is returning loginname in place of user id:

image

Is this change expected?

**Comment by sympmarc** [comment]
Definitely an improvement, @estruyf and @AsishP! Thanks for digging into this.

Getting the claim back for the id does make some sense, since the selected user may not be in the User Information List yet. (In the previous iteration, since the only users returned were from the current site, they were guaranteed to be in the UIL.)

I think we need to then ensure the user(s) are added to the UIL with a call something like this:

``` typescript
  private _getPeoplePickerRequestedBy(items: any[]): void {
    var updateRequest: IShipmentRequest = this.state.newRequest;
    sp.web.ensureUser(items[0].secondaryText).then((user) => {
      updateRequest.ShipmentRequestor.id = user.data.Id.toString() as string;
      updateRequest.ShipmentRequestor.title = user.data.Title;
      this.setState({
        newRequest: updateRequest
      });
    });
  }
```

**Comment by estruyf** [comment]
@ManiKum when you do the tenant search, you indeed get the user claim. As the API doesn't return the user ID of the UIL as @sympmarc explained. We could indeed add an implementation as @sympmarc provided, or we could also leave it up to the developer. IMO it all depends on what you want to do eventually with the selected user object.

About the `defaultSelectedUsers` property`, can you explain this a bit more? How it currently works is that it validates against the API if the user exists, if he/she is retrieved, they will be added to the control as a selected user.

**Comment by sympmarc** [comment]
It might be a nice option to add `ensureUser` as a parameter? If that was `true`, then then the picker *could* return the local user object. If `false`, it would return the people picker object.

Not sure how best to implement this, but it seems to make sense to tuck it in somehow.

**Comment by estruyf** [comment]
@sympmarc I actually like that idea. Let me try to implement this.

**Comment by estruyf** [comment]
@sympmarc and @ManiKum the `ensureUser` ability has been included to the control. By default, this setting is `false` and returns the user login name. If set to `true`, it will validate the user against the current site and return its ID instead. A new beta is out and available to test.

**Comment by sympmarc** [comment]
@estruyf - In my initial testing, this is working great. Thanks for adding `ensureUser`.

**Comment by estruyf** [comment]
Thanks @sympmarc for testing it out. Will release the public version later this week.

**Comment by AsishP** [comment]
Hi @estruyf , I tried to merge the changes into this PR but there were too many conflicts and didn't know if I was merging it correctly. So I think it is safe for me to close this PR and we go with your commits. Thanks, please let me know.

**Comment by estruyf** [comment]
Yes, we can close this PR.

**Pull request closed without merging**
