### PR TITLE
Live persona card

### LINKED ISSUE #259: New Control: Persona Card
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.12.0]

#### Expected / Desired Behavior / Question

The office ui fabric library provides a way to create a persona card that looks and feels like the out-of-the-box persona card in SharePoint. However, it requires the developer to do all the work to retrieve the information.
Example Persona Card
[Picture credit Heinrich Ulbricht](https://sharepoint.stackexchange.com/questions/259908/how-to-display-the-sharepoint-live-persona-card/259930#259930)

While it ultimately gives developers full control over what to render in the persona card, there are times where a developer just wants to render a standard/out-of-the-box persona card in their custom solutions.

Would it be useful to have a standard control to render an out-of-the-box persona card?

#### Observed Behavior
Office UI Fabric offers persona card control, but does not retrieve data for you.

#### Steps to Reproduce
1. Go to the [Office UI Fabric example](https://developer.microsoft.com/en-us/fabric-js/components/personacard/personacard) and copy into your own solution.
2. Control will require you to populate the data

> This idea originated from a [StackExchange post from Heinrich](https://sharepoint.stackexchange.com/questions/259908/how-to-display-the-sharepoint-live-persona-card/259930#259930). If you think it's a good idea, he deserves the credit. If you think it's a bad idea, I deserve the credit :-)

Thanks!

### PR DESCRIPTION
**Pull request by hugoabernier**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | Replaces PR #352, fixes #259 

#### What's in this Pull Request?

> Second attempt at submitting this. I included the wrong files in the previous one

Creates a wrapper around any HTML element that will present an Office 365 live persona card when users mouse over.

If you omit HTML elements, it will automatically render a default PersonaCard for the specified user.

This is the first version to resolve #259. I would like to look for opportunities to integrate with the `FieldUserRenderer` control and avoid duplicated code.

LivePersonaCard

### CODE REVIEW

**Comment by wobba** [comment]
The LPC is currently a first party component within Microsoft. We are aware of this approach taken to piggy-back on the person web part, which is not officially supported.

We will let this PR stay for now until we can verify if we can support this approach somehow. At least in a semi-official way, as we do understand the usecase for this 100%.

**Comment by hugoabernier** [comment]
Thanks @wobba, completely understand. Is there anything the community can do to help with this? E.g.: uservoice, etc.?

**Comment by wobba** [comment]
I'm tasked with evaluating pro/cons, why etc. Could take a little time, as there are multiple angels to cover. If I take too long reporting progress, remind me. Having a user voice for this is smart (if there isn't one).

**Comment by hugoabernier** [comment]
I added a uservoice entry for this, please vote if this is something that would be useful to you.
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38451154-provide-support-for-livepersonacard-in-3rd-party-s

**Comment by wobba** [comment]
@hugoabernier would you be willing to add lpc via https://docs.microsoft.com/nb-no/graph/toolkit/overview#using-the-components-with-react-angular-and-other-frameworks ?

**Comment by hugoabernier** [comment]
I'm open to it. 

The idea of the LPC was to make it easy to add a persona card without having to add any additional code to authorize or retrieve the user info. 

If the LPC as implemented in my PR will cause support issues, then using the Person-Card is the next best thing, and that's what we should do.

But I wonder if it would add little value (or no value at all) and would be better for people to just use https://docs.microsoft.com/en-us/graph/toolkit/components/person-card rather than introducing *another* LPC control for the sake of it.

I always assumed that the vision of SPFx is that 3rd-party developers will be able to build the same/similar applications as 1st-party developers, and that the sp-dev-fx-controls-react library aimed to bridge the gaps between what SPFx offers out-of-the-box and what developers needs to be standard 1st-party-like web parts. 

The persona card (in whatever implementation) aims to make it easy for developers to provide the same "people-centric" user experience that 1st-party SharePoint web parts provide. Users know that in 1st-party web parts, when you mouse over a person's name, you get their information.  We should strive to offer a component that makes it easy for 3rd party developers to offer the same experience.

I'd like to see what other contributors/the community think?

This isn't about what I need, it's about what the greater community needs. Whatever the decision, I'll gladly oblige. I'm trying to be helpful, not cause trouble :-)

**Comment by AJIXuMuK** [comment]
I'm ok with reusing Graph Toolkit.
But.
I think if we implement LPC, it shouldn't be hover-over only control...
I would like to render "see more" part of the OOTB component for example in a panel. Kinda "detailed" persona card :)

I mean this one:
Screen Shot 2019-09-27 at 10 23 01 AM

**Comment by wobba** [comment]
I'll check the toolkit implementation and see what makes the most sense (just discovered it today), so might still make sense for an SPFX version. API wise more and more is coming via the Graph for 3rd party, and reusing the people webpart LPC can in theory break as well.

If the Graph LPC is different, then that's not good imo.

**Comment by heinrich-ulbricht** [comment]
@wobba @hugoabernier Long time no see :) I'm again in a project where I basically have the requirement to add _the same_ persona card as the users see in SharePoint. We need the solution proposed by @hugoabernier and might go for it this time (if it still runs - if not then not).

I understand that making this internal component accessible for developers might slow down the development of this component throughout SharePoint. But alas. Just wanted to add our requirements as a data point to the discussion.

**Comment by wobba** [comment]
@heinrich-ulbricht thank you, and I'm still working on this. Things are changing in the back end as well, so the "hack" may stop working at some point. There are some technical challenges and hoops to go thru as well, and the issue is not forgotten.

I'll close this one now, as the implementation in the PR will not be the one we would support going forwards if/when we resolve this.

**Comment by MrTantum** [comment]
@wobba Any updates regarding this topic? It's again 5 month later. 

Graph Toolkit (and pure SPFX) is not an option for us because we want to have the Persona Cards on SharePoint modern **and** SharePoint Classic pages (e.g. in Classic Search Result Templates).

If nothing is available yet. We would give @hugoabernier control a try by rebuilding it in our solution and otherwise if this does not work use [Fabric UI's Persona card](https://developer.microsoft.com/en-us/fabric-js/components/personacard/personacard) as a fallback.

**Comment by wobba** [comment]
Hi, I got a followup last week actually and forgot to share. Due to the way the LPC is made as a component there won't be any official support for at least the next 6 months. Not the best of news unfortunately.

**Comment by MrTantum** [comment]
Even though it's bad news thanks for the feedback!

**Comment by sympmarc** [comment]
IMO, no solution is NOT better than a temporary solution. As it turns out, I need tois *today*, so I'm stuck in the middle.

**Comment by wobba** [comment]
@sympmarc need and want are two different things :) I feel your pain, so I would possibly go with the "hacky" solution at the expense of it might stop working as things most likely will change, but I'm not sure when.

**Comment by FvantHoff** [comment]
I would like the option to be built into Peole Finder to disable the mobile number. There are users who do not want their private number to be visible to everyone. The mobile number is used by PointSharp, among others, an app that sends an SMS when you need to go to a certain site that requires verification. According to the General Data Protection Regulation, privacy is violated if the mobile number is visible without permission.

**Comment by wobba** [comment]
@wictorwilen for awareness of the last comment.

**Comment by alicelupsan** [comment]
@wictorwilen  we would like to include this Live Persona Card in our product, when will a supported API be available for displaying this?

**Pull request closed without merging**
