### PR TITLE
Added defaults to PeoplePicker doc

### PR DESCRIPTION
**Pull request by sympmarc**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | Docs suggestion

#### What's in this Pull Request?
Example for displaying defaults for using the PeoplePicker control - issue #158

### CODE REVIEW

**Comment by tsekityam** [comment]
@sympmarc , 

I have introduced a new property `suggestionsLimit` to the picker, which is for limiting the number of suggestions to user. The property is in the dev branch but not yet land on the master branch. 

https://github.com/SharePoint/sp-dev-fx-controls-react/blob/84fa3366b390ae54276e6a031f4c0873ead54dc6/src/controls/peoplepicker/IPeoplePicker.ts#L31-L34 

Although I added the description of the new property in the code, I forgot to update the document. Could you please help me add the new property to the document?

Thanks,
Kit

**Comment by sympmarc** [comment]
@tsekityam:

Done, but it sort of seems like the doc change should be in your PR so they live together.

M.

**Comment by tsekityam** [comment]
It was landed in the dev branch 
https://github.com/SharePoint/sp-dev-fx-controls-react/commit/b93caa5fd3ac9616a82cbb7164c28d47beabaee7#diff-c193af510d00678280f780917a409152, perhaps you should rebase your branch and you should see the property at the bottom of the table.

**Comment by estruyf** [comment]
Thanks @sympmarc this makes things a lot easier indeed. I had to manually do the merge, but it's in.

**Comment by sympmarc** [comment]
@estruyf If you think adding the defaults the way I did for the PeoplePicker is useful, let me know and I'll try to puzzle out some of the others.

Sorry about the merge difficulties. It was probably because I added the additional default above after the fact.

**Pull request closed without merging**
