### PR TITLE
New Control: Attachments

### PR DESCRIPTION
**Pull request by sympmarc**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

It looks like there is an existing PR #177 for a List-Item-Attachments control from @joaojmendes, but I hadn't seen it before I build this for my own use. I figured I'd submit this anyway, since @joaojmendes' version seems to be on hold.

### CODE REVIEW

**Comment by estruyf** [comment]
@sympmarc @joaojmendes I was checking both of your list item attachment controls and I see that you both used `@pnp/js`. Would any of you be able to create it without that dependency? Calling the SharePoint APIs directly is significantly decreasing the bundle size.

**Comment by sympmarc** [comment]
Working on it...

**Comment by estruyf** [comment]
Awesome @sympmarc!

**Comment by sympmarc** [comment]
Looks like @joaojmendes beat me to it. Let me know if you still want me to do anything; otherwise, I'll hold.

**Comment by joaojmendes** [comment]
Hello,

Sorry for the later answer 😊. I did the changes, but only now I have opportunity to send the e-mail.

Thank you.

**Comment by estruyf** [comment]
@sympmarc the control from @joaojmendes has now been merged. Feel free to test it out and enhance it if necessary.

I'll close this PR for now.

**Pull request closed without merging**
